# Config file for available search engines

development:
  :yandex: "http://webmaster.yandex.ru/wmconsole/sitemap_list.xml?host=%s"
  :google: "http://www.google.com/webmasters/sitemaps/ping?sitemap=%s"

production:
  :yandex: "http://webmaster.yandex.ru/wmconsole/sitemap_list.xml?host=%s"
  :google: "http://www.google.com/webmasters/sitemaps/ping?sitemap=%s"
  :ask: "http://submissions.ask.com/ping?sitemap=%s"
  :bing: "http://www.bing.com/webmaster/ping.aspx?siteMap=%s"
  :sitemap_writer: "http://www.sitemapwriter.com/notify.php?crawler=all&url=%s"

test:
  :yandex: "http://webmaster.yandex.ru/wmconsole/sitemap_list.xml?host=%s"
  :google: "http://www.google.com/webmasters/sitemaps/ping?sitemap=%s"
  :ask: "http://submissions.ask.com/ping?sitemap=%s"
  :bing: "http://www.bing.com/webmaster/ping.aspx?siteMap=%s"
  :sitemap_writer: "http://www.sitemapwriter.com/notify.php?crawler=all&url=%s"
